### ISSUE TITLE
web_url is not passed back to the github pipeline

### ISSUE THREAD

**Issue by wdconinc** [eic/trigger-gitlab-ci#2]

**Comment by peterfpeterson** [comment]
It looks like you did this a yesterday, but the `@v1` of your hook doesn't include it even though the `git tag` does. Did you move an existing tag?

**Comment by wdconinc** [comment]
That seems to be what one is forced to do with GitHub actions if you also want to use semantic versioning. Eg, if you have v1.0.0, fix a bug, and retag v1.0.1, then you have to remove the v1 which was equal to v1.0.0 and create a new v1 tag to v1.0.1. Does that answer your question?

**Comment by wdconinc** [comment]
But maybe I messed something up?

**Comment by wdconinc** [comment]
In any case the web_url function isn't being passed to the next step yet, so this issue is not fixed in main either.

**Comment by peterfpeterson** [comment]
It isn't being printed in the current use either. I think tagging the current head as v2 will get that part working.

**Comment by peterfpeterson** [comment]
I found [this documentation](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions) which says you need to declare the output, but I haven't had luck making it work.

**Comment by wdconinc** [comment]
Closing since now implemented.
